### ISSUE TITLE
Plugin load too high.

### ISSUE THREAD

**Issue by ccyounga** [en0tuk/Advanced-eHideTags-public#1]
**Describe the bug**
Plugin load too high.

**To Reproduce**
1. Go to 'timings'
2. Click on 'timings on'
3. Scroll down to 'timings paste - plugins(avg, lag)'

**Expected behavior**

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://imgur.com/VUFj5KO)

**Server Environment (please complete the following information):**
git-Paper-386 (MC: 1.18.2)

**Plugin Version:**
Which plugin version do you use.

**Additional context**
[Add any other context about the problem here.](https://imgur.com/VUFj5KO)

**Comment by en0tuk** [comment]
Can you send a link to these timings?

**Comment by en0tuk** [comment]
Issue author not responding too long so i closed issue
