### ISSUE TITLE
Team name 'Advanced-eHideTags' is longer than the limit of 16 characters

### ISSUE THREAD

**Issue by ghost** [en0tuk/Advanced-eHideTags-public#2]
**Describe the bug**
when the server starts, the message appears in the console "https://mcpaste.io/3a4798f6ca09e7b4 ", the plugin does not start.

**Server Environment (please complete the following information):**
 - OS: Linux
 - Server Kernel: PurpurMC
 - Version: 1.17.1 (1.17.1-1428)

**Plugin Version:**
1.0.0 from modrinth

**Comment by en0tuk** [comment]
Fixed https://modrinth.com/plugin/eht/version/rfe3DfuP
