### ISSUE TITLE
Overloads according to timings reports

### ISSUE THREAD

**Issue by ccyounga** [en0tuk/Advanced-eHideTags-public#3]
The latest and only version of the plugin. Server on paper 1.18.2.

The plugin causes loads according to timings reports, see for yourself:
https://timings.aikar.co/dev/?id=9519689cbec84e0d9ee77ab665451cd5#timings
[img]https://i.imgur.com/tEhmEeE.png[/img]

**Comment by en0tuk** [comment]
I see that you have spark installed, send a profiler from it

**Comment by en0tuk** [comment]
Let 's talk in Russian for your convenience in the future because looks like it's your native language
